spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jst-mes-prd?serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 50
#      idle-timeout: 1000
#      pool-name: blah
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 9999
mybatis:
  mapper-locations: mapper/*.xml